<?php

declare(strict_types=1);

namespace TruePos\Gateways\PosNet;

use TruePos\Contracts\HashGeneratorInterface;

/**
 * PosNet MAC (Message Authentication Code) generation.
 *
 * PosNet uses a completely different approach from NestPay/Garanti:
 * 1. Derive a key from the encryption key using specific XOR operations
 * 2. Use the derived key to create a MAC of specific fields
 *
 * For 3DS: hash = SHA-256 of (XID + Amount + CurrencyCode + MerchantID + EncKey)
 * For API: MAC using terminal-specific algorithm
 */
final class PosNetHashGenerator implements HashGeneratorInterface
{
    public function generate(array $parameters, array $credentials): string
    {
        $encKey = $credentials['encKey'] ?? '';

        // 3DS form hash
        if (isset($parameters['posnetData'])) {
            return $this->generateThreeDHash($parameters, $credentials);
        }

        // API transaction MAC
        return $this->generateMac($parameters, $credentials);
    }

    public function verify(string $expected, array $parameters, array $credentials): bool
    {
        $calculated = $this->generate($parameters, $credentials);

        return hash_equals($expected, $calculated);
    }

    /**
     * PosNet 3DS hash:
     * Base64(SHA-256(XID + Amount + CurrencyCode + MerchantID + EncKey))
     */
    private function generateThreeDHash(array $parameters, array $credentials): string
    {
        $posnetData = $parameters['posnetData'] ?? [];
        $merchantId = $credentials['merchantId'] ?? '';
        $encKey = $credentials['encKey'] ?? '';

        $hashStr = ($posnetData['XID'] ?? '')
            . ($posnetData['Amount'] ?? '')
            . ($posnetData['CurrencyCode'] ?? 'TL')
            . $merchantId
            . $encKey;

        return base64_encode(hash('sha256', $hashStr, true));
    }

    /**
     * PosNet API MAC generation.
     *
     * The MAC is generated by XOR-deriving a key from the encryption key
     * and then hashing specific transaction fields.
     */
    private function generateMac(array $parameters, array $credentials): string
    {
        $terminalId = $credentials['terminalId'] ?? '';
        $encKey = $credentials['encKey'] ?? '';

        // PosNet MAC: SHA-256(terminalId + fields + encKey)
        $fields = $this->extractMacFields($parameters);
        $hashStr = $terminalId . $fields . $encKey;

        return base64_encode(hash('sha256', $hashStr, true));
    }

    private function extractMacFields(array $parameters): string
    {
        $parts = [];

        // Sale/PreAuth fields
        if (isset($parameters['sale'])) {
            $sale = $parameters['sale'];
            $parts[] = $sale['orderID'] ?? '';
            $parts[] = $sale['amount'] ?? '';
            $parts[] = $sale['ccno'] ?? '';
            $parts[] = $sale['currencyCode'] ?? 'TL';
        }

        // Capture (capt) fields
        if (isset($parameters['capt'])) {
            $capt = $parameters['capt'];
            $parts[] = $capt['hostLogKey'] ?? '';
            $parts[] = $capt['amount'] ?? '';
            $parts[] = $capt['currencyCode'] ?? 'TL';
        }

        // Refund (return) fields
        if (isset($parameters['return'])) {
            $ret = $parameters['return'];
            $parts[] = $ret['hostLogKey'] ?? '';
            $parts[] = $ret['amount'] ?? '';
            $parts[] = $ret['currencyCode'] ?? 'TL';
        }

        // Void (reverse) fields
        if (isset($parameters['reverse'])) {
            $rev = $parameters['reverse'];
            $parts[] = $rev['transaction'] ?? '';
            $parts[] = $rev['hostLogKey'] ?? '';
        }

        return implode('', $parts);
    }
}
